using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cs2Ts;

class Program
{
    static async Task Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.WriteLine("Usage: Cs2Ts <outputFolder>");
            return;
        }

        var outputRoot = Path.GetFullPath(args[0]);
        
        // Clear the target directory if it exists
        if (Directory.Exists(outputRoot))
        {
            Console.WriteLine($"Clearing target directory: {outputRoot}");
            // First delete all TypeScript files
            foreach (var file in Directory.GetFiles(outputRoot, "*.ts", SearchOption.AllDirectories))
            {
                File.Delete(file);
                Console.WriteLine($"Deleted file: {file}");
            }
            
            // Then clean up empty directories (bottom-up approach)
            CleanEmptyDirectories(outputRoot);
        }
        
        Directory.CreateDirectory(outputRoot);

        var projectRoot = Directory.GetCurrentDirectory();
        var sourceFiles = Directory.EnumerateFiles(projectRoot, "*.cs", SearchOption.AllDirectories)
                                   .Where(p => !p.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase) &&
                                               !p.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase) &&
                                               !p.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase));

        var tasks = new List<Task>();
        foreach (var file in sourceFiles)
        {
            var relativePath = Path.GetRelativePath(projectRoot, file);
            var fileText = await File.ReadAllTextAsync(file);
            var tree = CSharpSyntaxTree.ParseText(fileText);
            var root = await tree.GetRootAsync();

            var convertNodes = root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>()
                                   .Where(n => HasConvertToTsAttribute(n.AttributeLists));

            foreach (var node in convertNodes)
            {
                tasks.Add(Task.Run(() =>
                {
                    var tsContent = TypeScriptGenerator.Generate(node, tree);
                    var targetPath = Path.Combine(outputRoot, Path.ChangeExtension(relativePath, ".ts"));
                    var targetDir = Path.GetDirectoryName(targetPath)!;
                    Directory.CreateDirectory(targetDir);
                    File.WriteAllText(targetPath, "// This file has been generated by Cs2Ts\n// Do not edit as it will be overwritten\n"+tsContent);
                    Console.WriteLine($"Generated {relativePath} -> {Path.GetRelativePath(projectRoot, targetPath)}");
                }));
            }
        }

        await Task.WhenAll(tasks);
        Console.WriteLine("TypeScript generation completed successfully.");
    }

    static bool HasConvertToTsAttribute(SyntaxList<AttributeListSyntax> lists)
    {
        foreach (var list in lists)
        {
            foreach (var attr in list.Attributes)
            {
                var name = attr.Name.ToString();
                if (name is "ConvertToTs" or "ConvertToTsAttribute") return true;
            }
        }
        return false;
    }

    // Recursively removes empty directories
    static void CleanEmptyDirectories(string directory)
    {
        // Process all subdirectories first (bottom-up)
        foreach (var dir in Directory.GetDirectories(directory))
        {
            CleanEmptyDirectories(dir);
        }
        
        // Check if this directory is now empty
        if (Directory.GetFiles(directory).Length == 0 && 
            Directory.GetDirectories(directory).Length == 0 &&
            !directory.Equals(Path.GetFullPath(directory), StringComparison.OrdinalIgnoreCase))
        {
            Directory.Delete(directory);
            Console.WriteLine($"Deleted empty directory: {directory}");
        }
    }
}
