// This file has been generated by Cs2Ts
// Do not edit as it will be overwritten
import type { ReactNode } from 'react';

import type { OtherModel } from './OtherModel';
import { UiColor } from './UiColor';

/**
 * Demonstrates a rich model for TypeScript generation.
 */
export interface TestModel {
  /**
   * Display name for the model.
   */
  name: string | null;
  age: number;
  birthDate: Date | null;
  isActive: boolean | null;
  simpleAction: () => void | null;
  actionWithParam: (arg: string) => void | null;
  actionWithTwoParams: (arg1: string, arg2: number) => void | null;
  funcWithReturn: () => string | null;
  funcWithParamAndReturn: (arg: number) => string | null;
  funcWithTwoParamsAndReturn: (arg1: string, arg2: number) => boolean | null;
  reactContent: ReactNode;
  domElement: HTMLElement;
  other: OtherModel | null;
  defaultColorLiteral: typeof UiColor.Black;
  nullableAction: () => void | null;
  nullableFunc: () => string | null;
}

export const DefaultColor: UiColor = UiColor.Black;

/**
 * Represents a percussive sound that can be used in beat generation.
 */
export interface BeatSound {
  /**
   * Human readable name of the sound.
   */
  name: string;
  /**
   * Identifier used to locate the sound asset.
   */
  soundId: string;
}

/**
 * Default metronome sound.
 */
export const Default: BeatSound = {
  name: "Default",
  soundId: "Default"
};

/**
 * Click sound that accentuates beats.
 */
export const Click: BeatSound = {
  name: "Click",
  soundId: "Click"
};

/**
 * A marker interface for actions that can contain other actions. We don't have a GetChildren() method, because we're using C# to Ts conversion.
 */
export interface ICompositeAction {
}