// This file has been generated by Cs2Ts
// Do not edit as it will be overwritten
export const UiColor = {
  Transparent: 0,
  Black: 1,
  White: 2,
  Magenta: 10,
} as const;

export type UiColor = (typeof UiColor)[keyof typeof UiColor];

export const UiColorName = {
  0: 'Transparent',
  1: 'Black',
  2: 'White',
  10: 'Magenta',
} as const satisfies Record<UiColor, keyof typeof UiColor>;